name: braid-opto-arena-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - matplotlib
  - numpy
  - pandas
  - tqdm
  - pyqtgraph
  - pre-commit
  - pyserial
  - requests
  - gitpython
  - pyzmq
  - pyqt
  - ruff
  - scipy
  - pygame
