name: braid-trigger-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - matplotlib
  - numpy
  - pandas
  - tqdm
  - pyqtgraph
  - pre-commit
  - pip:
    - pyserial
    - requests
    - GitPython
    - pygame
    - pyzmq
    - PyQt5
    - ruff