name: braid-opto-arena

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - tqdm
  - pyqtgraph
  - pre-commit
  - pyserial
  - requests
  - gitpython
  - pyzmq
  - pyqt
  - ruff
  - scipy
  - pygame
