max_runtime = 12 # Maximum runtime in hours

[arduino_devices]
opto_trigger = '/dev/opto_trigger'
camera_trigger = '/dev/camera_trigger'

# opto trigger parameters
[trigger_params]
type = "zone"             # Type of trigger
min_trajectory_time = 1.0 # Minimum trajectory time in seconds
min_trigger_interval = 10 # Minimum time between activations in seconds
min_radius = 0.05         # Minimum radius for activation in meters
zmin = 0.15               # Minimum z for activation in meters
zmax = 0.25               # Maximum z for activation in meters
xmin = -0.049             # Minimum x for activation in meters
xmax = 0.0757             # Maximum x for activation in meters
ymin = -0.04123           # Minimum y for activation in meters
ymax = 0.082              # Maximum y for activation in meters
center_x = 0              # Arena center x in meters
center_y = 0              # Arena center y in meters

# opto light parameters
[opto_params]
active = false
duration = 300  # Duration in milliseconds
intensity = 255 # Intensity in 0-255 range
frequency = 0   # Frequency in Hz
sham_perc = 0.1 # Percentage of sham trials

# stimulus setup
[stim_params]

# main window setup
[stim_params.window]
size = [640, 128] # Window size in pixels
pos = [0, 0]      # Position
fullscr = false   # Full screen mode
screen = 1        # Screen number
color = [1, 1, 1] # Color in RGB
units = "pix"     # Units

# static stimulus setup
[stim_params.static]
active = true
image = "modules/static.jpg" # Path to static image

# grating stimulus setup
[stim_params.grating]
active = false
frequency = 0   # Frequency
orientation = 0 # Orientation
direction = 0   # Direction
color = "black" # Color

# looming stimulus setup
[stim_params.looming]
active = true
stim_type = "exponential" # Stimulus type
position = "closed-loop"  # Position
max_radius = 64           # Maximum radius
duration = 300            # Duration
color = "black"           # Color

# high-speed camera setup
[highspeed]
active = true
type = "ximea" # Type of high-speed camera

# high-speed cameras list
[highspeed.cameras]
camera1 = "23047980" # Camera 1 serial number
camera2 = "23096298" # Camera 2 serial number
camera3 = "23088879" # Camera 3 serial number
camera4 = "23088882" # Camera 4 serial number

# high-speed camera parameters
[highspeed.parameters]
pre_trigger_mode = true      # Pre-trigger mode enabled
time_before = 1              # Time before trigger in seconds
time_after = 2               # Time after trigger in seconds
fps = 500                    # Frames per second
exposure_time = 1900         # Exposure time in microseconds
sensor_readout_mode = "Fast" # Sensor readout mode
