[package]
name = "xiapi_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xiapi = { git = "https://github.com/Ximea-GmbH/xiapi" }